command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: GEOCODE_XYZ_SECRET_KEY
    value: "geocode-xyz-api-key"
  - name: GEOPY_APP_SECRET_KEY
    value: "geopy-app-name"
